### ISSUE TITLE
Internal error with "Save & Close"

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#120]
I clicked on Save & Close on my FINU102 pipeline and I got an internal error. From frontend.log:

<pre><code>java.lang.NullPointerException: null
        at com.vaadin.ui.CustomTable.findNumRowsToPaint(CustomTable.java:3709) ~[filteringtable-0.9.4.v7.jar:7.1.8]
        at com.vaadin.ui.CustomTable.doPaintContent(CustomTable.java:3217) ~[filteringtable-0.9.4.v7.jar:7.1.8]
        at com.vaadin.ui.CustomTable.paintContent(CustomTable.java:3203) ~[filteringtable-0.9.4.v7.jar:7.1.8]
        at org.tepi.filtertable.FilterTable.paintContent(FilterTable.java:69) ~[filteringtable-0.9.4.v7.jar:0.9.4.v7]
        at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:81) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:106) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:149) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:97) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) ~[vaadin-server-7.1.8.jar:7.1.8]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:79) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722) [servlet-api-3.0.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [tomcat-catalina-7.0.28.jar:7.0.28]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002) [tomcat-coyote-7.0.28.jar:7.0.28]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579) [tomcat-coyote-7.0.28.jar:7.0.28]
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote-7.0.28.jar:7.0.28]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_65]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_65]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]</code></pre>

**Comment by tomas-knap** [comment]
Cannot be reproduced
