### ISSUE TITLE
number of running priority - problem 

### ISSUE THREAD

**Issue by marcoony** [UnifiedViews/Core#198]
Execution of ppl wasn't running, but ppl seemed like is running in Execution monitor. 
It was unable to run another ppl. 
The logs of executed pipeline weren't displayed in browse/log. 

Probably problem with logging into databases caused deadlock in Engine. 

```
2014-10-08 13:37:40,156 [dpu: Isvav] DEBUG exec:1161 dpu:2215 c.c.mff.xrg.uv.boost.dpu.advanced.DpuAdvancedBase - Executing 'CachedFileDownloader' with on 'PRE_EXECUTE' point
2014-10-08 13:37:40,156 [dpu: Isvav] DEBUG exec:1161 dpu:2215 c.c.m.x.u.s.s.xml.SerializationXmlGeneralImpl - convert for: Configuration
2014-10-08 13:37:40,157 [dpu: Isvav] INFO  exec:1161 dpu:2215 c.c.mff.xrg.uv.boost.dpu.advanced.DpuAdvancedBase - innerExecute:start
2014-10-08 13:37:40,157 [dpu: Isvav] DEBUG exec:1161 dpu:2215 cz.cuni.mff.xrg.uv.extractor.isvav.Isvav - Extracting from 1991 to 2014
2014-10-08 13:37:40,158 [dpu: Isvav] INFO  exec:1161 dpu:2215 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUMessage - DPU 'Isvav' publish message short: 'Extracting files ...' long: ''
2014-10-08 13:37:40,248 [taskScheduler-3] DEBUG exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - flush() : get connection
2014-10-08 13:37:40,248 [taskScheduler-3] TRACE exec: dpu: c.c.mff.xrg.odcs.backend.logback.SqlAppenderImpl - flushIntoDatabase called for 38 logs
2014-10-08 13:37:40,250 [taskScheduler-3] INFO  exec: dpu: org.eclipse.persistence.logging.default - 2014-10-08 13:37:40.25--UnitOfWork(730709474)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was74104 seconds ago.The last packet sent successfully to the server was 74104 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT id AS a1, DPU AS a2, EXECUTION AS a3, logLevel AS a4, message AS a5, relative_id AS a6, logger AS a7, stack_trace AS a8, timestmp AS a9 FROM logging WHERE (EXECUTION = ?) ORDER BY id DESC LIMIT ?, ?
        bind => [1161, 0, 1]
Query: ReadAllQuery(referenceClass=Log sql="SELECT id AS a1, DPU AS a2, EXECUTION AS a3, logLevel AS a4, message AS a5, relative_id AS a6, logger AS a7, stack_trace AS a8, timestmp AS a9 FROM logging WHERE (EXECUTION = ?) ORDER BY id DESC LIMIT ?, ?").
2014-10-08 13:37:40,315 [dpu: Isvav] INFO  exec:1161 dpu:2215 cz.cuni.mff.xrg.uv.extractor.isvav.Isvav - Downloading: 0 records
2014-10-08 13:37:40,315 [dpu: Isvav] INFO  exec:1161 dpu:2215 c.c.m.x.u.b.dpu.addon.impl.CachedFileDownloader - get(Result-1991.zip, http://www.isvav.cz/export.zip;jsessionid=673C48C0CEC6576917FAF55949087662?entityType=result&exportType=xls) - file from cache
2014-10-08 13:37:40,479 [dpu: Isvav] TRACE exec:1161 dpu:2215 o.o.repository.sail.helpers.SailUpdateExecutor - Incoming update expression:
Modify
   StatementPattern
      Var (name=s)
      Var (name=predicate)
      Var (name=object)
   StatementPattern
      Var (name=s)
      Var (name=-const-http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName-uri, value=http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName, anonymous)
      Var (name=symbolicName)

2014-10-08 13:37:40,479 [dpu: Isvav] TRACE exec:1161 dpu:2215 org.openrdf.sail.nativerdf.NativeStoreConnection - Incoming query model:
QueryRoot
   StatementPattern
      Var (name=s)
      Var (name=-const-http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName-uri, value=http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName, anonymous)
      Var (name=symbolicName)

2014-10-08 13:37:40,479 [dpu: Isvav] TRACE exec:1161 dpu:2215 org.openrdf.sail.nativerdf.NativeStoreConnection - Optimized query model:
QueryRoot
   StatementPattern
      Var (name=s)
      Var (name=-const-http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName-uri, value=http://unifiedviews.eu/DataUnit/MetadataDataUnit/symbolicName, anonymous)
      Var (name=symbolicName, value="Result-1991.zip")
2014-10-08 13:37:40,647 [dpu: Isvav] INFO  exec:1161 dpu:2215 cz.cuni.mff.xrg.odcs.backend.dpu.event.DPUMessage - DPU 'Isvav' publish message short: 'File extracted 0/24' long: 'Extracted file saved into: Result-1991.zip'
2014-10-08 13:37:46,628 [taskScheduler-7] TRACE exec: dpu: c.c.mff.xrg.odcs.commons.app.scheduling.Schedule - onTimeCheck started
2014-10-08 13:37:54,538 [taskScheduler-6] DEBUG exec: dpu: cz.cuni.mff.xrg.odcs.backend.execution.Engine - >>> Entering checkJobs()
2014-10-08 16:08:01,912 [Thread-4] TRACE exec: dpu: c.c.m.x.o.c.app.module.impl.FileNotifierClient - Stopping FileNotifierServer ...
2014-10-08 16:08:02,095 [File notifier server] TRACE exec: dpu: c.c.m.x.o.c.app.module.impl.FileNotifierClient - DPU's change watcher has been interrupted.
2014-10-08 16:08:02,095 [Thread-4] TRACE exec: dpu: c.c.m.x.o.c.app.module.impl.FileNotifierClient - FileNotifierServer has been stopped.
2014-10-08 16:08:02,129 [Thread-4] INFO  exec: dpu: org.eclipse.persistence.logging.connection - 2014-10-08 16:08:02.129--ServerSession(1343863107)--Connection(367494946)--disconnect
2014-10-08 16:08:02,129 [Thread-4] INFO  exec: dpu: org.eclipse.persistence.logging.connection - 2014-10-08 16:08:02.129--ServerSession(1343863107)--file:/usr/share/unifiedviews/lib/commons-app-1.3.2-SNAPSHOT.jar_odcs logout successful
2014-10-08 16:08:02,131 [taskScheduler-3] INFO  exec: dpu: org.eclipse.persistence.logging.default - 2014-10-08 16:08:02.131--UnitOfWork(730709474)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, general error
Error Code: 0
Call: SELECT id AS a1, DPU AS a2, EXECUTION AS a3, logLevel AS a4, message AS a5, relative_id AS a6, logger AS a7, stack_trace AS a8, timestmp AS a9 FROM logging WHERE (EXECUTION = ?) ORDER BY id DESC LIMIT ?, ?
        bind => [1161, 0, 1]
Query: ReadAllQuery(referenceClass=Log sql="SELECT id AS a1, DPU AS a2, EXECUTION AS a3, logLevel AS a4, message AS a5, relative_id AS a6, logger AS a7, stack_trace AS a8, timestmp AS a9 FROM logging WHERE (EXECUTION = ?) ORDER BY id DESC LIMIT ?, ?").
2014-10-08 16:08:02,131 [taskScheduler-6] INFO  exec: dpu: org.eclipse.persistence.logging.default - 2014-10-08 16:08:02.131--UnitOfWork(554101715)--Communication failure detected when attempting to perform read query outside of a transaction. Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot get a connection, general error
Error Code: 0
Call: SELECT ID AS a1, NAME AS a2, VALUE AS a3 FROM runtime_properties WHERE (NAME = ?) LIMIT ?, ?
        bind => [backend.scheduledPipelines.limit, 0, 1]
Query: ReadAllQuery(referenceClass=RuntimeProperty sql="SELECT ID AS a1, NAME AS a2, VALUE AS a3 FROM runtime_properties WHERE (NAME = ?) LIMIT ?, ?").

```
from [backend.2014-10-08.0.log]

jstack log
```
java.lang.Thread.State: BLOCKED (on object monitor)
        at cz.cuni.mff.xrg.odcs.backend.execution.Engine.checkJobs(Engine.java:129)
        - waiting to lock <0x00007f6ca81f5a60> (a java.lang.Object)
        at cz.cuni.mff.xrg.odcs.backend.execution.Engine.onApplicationEvent(Engine.java:241)```

**Comment by tomas-knap** [comment]
Do not know how to reproduce

**Comment by marcoony** [comment]
The main problem has been that we still don't know how to reproduce.
