### ISSUE TITLE
frontend has stopped

### ISSUE THREAD

**Issue by marcoony** [UnifiedViews/Core#199]
suspect: ODCSApplicationServlet
super.service(request, response);

jstack
```
"http-bio-8080-exec-177" daemon prio=10 tid=0x00007f2fd01fd000 nid=0x5b58 waiting on condition [0x00007f2fc8e90000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000072c92a400> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
        at com.vaadin.server.VaadinService.lockSession(VaadinService.java:589)
        at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:625)
        at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:495)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1365)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:79)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        - locked <0x00000006fcc377f8> (a org.apache.tomcat.util.net.SocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
```
"http-bio-8080-exec-158" daemon prio=10 tid=0x00000000038b4000 nid=0x545f in Object.wait() [0x00007f2fc9cd9000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000006f7d9b250> (a org.apache.commons.pool.impl.GenericObjectPool$Latch)
        at java.lang.Object.wait(Object.java:503)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1104)
        - locked <0x00000006f7d9b250> (a org.apache.commons.pool.impl.GenericObjectPool$Latch)
        at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123)
        at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.connectInternal(DatasourceAccessor.java:346)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.connectInternal(DatabaseAccessor.java:307)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.reconnect(DatasourceAccessor.java:581)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.reconnect(DatabaseAccessor.java:1625)
        at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.incrementCallCount(DatasourceAccessor.java:321)
        - locked <0x00000006f7d9b1f0> (a org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:613)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991)
        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2738)
        at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2691)
        at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:495)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1168)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1127)
        at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:403)
        at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1215)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1740)
        at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
        at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:517)
        at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
        at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessReadBase.execute(DbAccessReadBase.java:133)
        at cz.cuni.mff.xrg.odcs.commons.app.user.DbUserImpl.getByUsername(DbUserImpl.java:35)
        at cz.cuni.mff.xrg.odcs.commons.app.facade.UserFacadeImpl.getUserByUsername(UserFacadeImpl.java:88)
        at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
        at com.sun.proxy.$Proxy33.getUserByUsername(Unknown Source)
        at cz.cuni.mff.xrg.odcs.commons.app.auth.PasswordAuthenticationProvider.retrieveUser(PasswordAuthenticationProvider.java:76)
at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:132)
        at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156)
        at cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService.login(AuthenticationService.java:96)
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.login(Login.java:126)
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.access$000(Login.java:39)
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login$2.buttonClick(Login.java:111)
        at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969)
        at com.vaadin.ui.Button.fireClick(Button.java:355)
        at com.vaadin.ui.Button.click(Button.java:344)
        at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:523)
        at com.vaadin.event.ActionManager.handleAction(ActionManager.java:235)
        at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81)
        at com.vaadin.event.ActionManager.handleAction(ActionManager.java:230)
        at com.vaadin.event.ActionManager.handleActions(ActionManager.java:213)
        at com.vaadin.ui.UI.changeVariables(UI.java:353)
        at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:396)
        at com.vaadin.server.communication.ServerRpcHandler.handleBurst(ServerRpcHandler.java:221)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:111)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:37)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:79)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        - locked <0x00000006f5c97188> (a org.apache.tomcat.util.net.SocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

frontend.log
```
2014-10-10 09:04:03,904 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2014-10-10 09:04:03.86--ServerSession(1047534301)--Connection(1839630004)--SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4,
USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?
        bind => [admin, 0, 1]
2014-10-10 09:04:03,988 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2014-10-10 09:04:03.986--ServerSession(1047534301)--SELECT 1
2014-10-10 09:04:04,208 [http-bio-8080-exec-10] INFO  org.eclipse.persistence.logging.default - 2014-10-10 09:04:04.164--UnitOfWork(53548664)--Communication failure detected when attempting to perform read query outside of a transaction.
 Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was46872 seconds ago.The last packet sent successfully to the server was 46872 seconds ago, which  is long
er than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Conne
ctor/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4, USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?
        bind => [admin, 0, 1]
Query: ReadAllQuery(referenceClass=User sql="SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4, USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?").
2014-10-10 09:04:04,249 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2014-10-10 09:04:04.248--ServerSession(1047534301)--Connection(196747755)--SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4,
USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?
        bind => [admin, 0, 1]
2014-10-10 09:04:04,271 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2014-10-10 09:04:04.271--ServerSession(1047534301)--SELECT 1
2014-10-10 09:04:04,336 [http-bio-8080-exec-10] INFO  org.eclipse.persistence.logging.default - 2014-10-10 09:04:04.32--UnitOfWork(53548664)--Communication failure detected when attempting to perform read query outside of a transaction.
Attempting to retry query. Error was: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was56302 seconds ago.The last packet sent successfully to the server was 56302 seconds ago, which  is long
er than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Conne
ctor/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4, USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?
        bind => [admin, 0, 1]
Query: ReadAllQuery(referenceClass=User sql="SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4, USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?").
```

**Comment by tomas-knap** [comment]
Do not know how to reproduce,
