### ISSUE TITLE
When trying to replace jar file with a different one, problem is not clearly presented to the user

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#23]
When replacing an existing jar file X, but accidentally selects jar file Y, which is already loaded as DPU template, a generic error appears: 

"Cannot replace DPU template"

But in the log, there is more useful message: 

2014-03-18 09:08:21,188 [http-bio-8080-exec-660] WARN  c.c.m.x.o.commons.app.module.DPUModuleManipulator - Failed to load bunle during replace.
cz.cuni.mff.xrg.odcs.commons.app.module.ModuleException: Failed to update bundle.
	at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.update(OSGIModuleFacade.java:203) ~[commons-app-1.0.0.jar:na]
	at cz.cuni.mff.xrg.odcs.commons.app.module.DPUModuleManipulator.replace(DPUModuleManipulator.java:309) ~[commons-app-1.0.0.jar:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.copyToTarget(DPUPresenterImpl.java:237) [DPUPresenterImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploaded(DPUPresenterImpl.java:217) [DPUPresenterImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploadedEventHandler(DPUPresenterImpl.java:278) [DPUPresenterImpl.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$15.uploadSucceeded(DPUViewImpl.java:637) [DPUViewImpl$15.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper.uploadSucceeded(AuthAwareUploadSucceededWrapper.java:50) [AuthAwareUploadSucceededWrapper.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:167) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:969) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:811) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.ui.Upload$1.streamingFinished(Upload.java:1070) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:567) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:432) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:395) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:280) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1371) [vaadin-server-7.1.8.jar:7.1.8]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238) [vaadin-server-7.1.8.jar:7.1.8]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:74) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.33]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931) [catalina.jar:7.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) [catalina.jar:7.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) [tomcat-coyote.jar:7.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.33]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
	at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: org.eclipse.osgi.framework.internal.core.Framework$DuplicateBundleException: Bundle "cz.cuni.mff.xrg.odcs.MetadataForm" version "1.0.0" has already been installed from: file:////data/odcs/target/dpu/MetadataForm/MetadataForm-1.0.0.jar
	at org.eclipse.osgi.framework.internal.core.Framework.createAndVerifyBundle(Framework.java:722) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.Framework.installWorkerPrivileged(Framework.java:942) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:845) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.Framework$1.run(Framework.java:1) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_40]
	at org.eclipse.osgi.framework.internal.core.Framework.installWorker(Framework.java:904) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.Framework.installBundle(Framework.java:840) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:137) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.installBundle(BundleContextImpl.java:131) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
	at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.update(BundleContainer.java:223) ~[commons-app-1.0.0.jar:na]
	at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.update(OSGIModuleFacade.java:201) ~[commons-app-1.0.0.jar:na]
	... 39 common frames omitted
2014-03-18 09:08:21,218 [http-bio-8080-exec-660] DEBUG org.eclipse.persistence.logging.sql - 2014-03-18 09:08:21.218--ServerSession(1794356567)--Connection(624302659)--SELECT ID, config_valid, description, jar_description, jar_directory, jar_name, name, configuration, visibility, TYPE, use_dpu_description, user_id, parent_id FROM dpu_template WHERE (ID = ?)
	bind => [226]

Solution: Please provide more information to the user, so that he is informed that he is trying to replace DPU template X with DPU template Y, which will not work.

**Comment by tomas-knap** [comment]
@skodape Is this still relevant?

**Comment by skodape** [comment]
I think it's but there are more steps, I would propose to close this issue and create new in as we come up against concrete situations (missing package, wrong dialog, etc .. )

**Comment by tomas-knap** [comment]
Closing, new issues will be created as we come accross the problems (this issue is almost 1 year old)
