### ISSUE TITLE
Backend stopped

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#244]
Now I am not sure what caused backend to stop, whether the exceptions or the DPU update, which is the last log line (developUK branch)
<pre><code>
2014-11-20 07:20:47,783 [dpu: [INTLIB] PSP Extractor] WARN  exec:84 dpu:2008 c.c.m.x.odcs.backend.db.SQLDatabaseReconnectAspect - failureTolerant has caught exception
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was72817 seconds ago.The last packet sent successfully to the server was 72817 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT ID FROM dpu_instance WHERE (ID = ?)
        bind => [2008]
Query: DoesExistQuery(referenceClass=DPUInstanceRecord sql="SELECT ID FROM dpu_instance WHERE (ID = ?)")
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[spring-tx-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[spring-tx-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387) ~[spring-tx-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$afterReturning$org_springframework_transaction_aspectj_AbstractTransactionAspect$3$2a73e96c(AbstractTransactionAspect.aj:78) ~[spring-aspects-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at cz.cuni.mff.xrg.odcs.commons.app.facade.DPUFacadeImpl.save(DPUFacadeImpl.java:270) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) ~[spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80) ~[spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at cz.cuni.mff.xrg.odcs.backend.db.SQLDatabaseReconnectAspect.failureTolerant(SQLDatabaseReconnectAspect.java:101) ~[backend-1.4.1-SNAPSHOT.jar:na]
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at com.sun.proxy.$Proxy30.save(Unknown Source) [na:na]
        at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onDPUEvent(EventListenerDatabase.java:29) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:46) [backend-1.4.1-SNAPSHOT.jar:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:280) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:264) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:257) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.opendata.linked.psp_cz.metadata.Extractor.innerExecute(Extractor.java:113) [bundlefile:na]
        at cz.cuni.mff.xrg.uv.boost.dpu.advanced.DpuAdvancedBase.execute(DpuAdvancedBase.java:223) [boost-dpu-1.1.2.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:231) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:369) [backend-1.4.1-SNAPSHOT.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:451) [backend-1.4.1-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
Caused by: javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was72817 seconds ago.The last packet sent successfully to the server was 72817 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT ID FROM dpu_instance WHERE (ID = ?)
        bind => [2008]
Query: DoesExistQuery(referenceClass=DPUInstanceRecord sql="SELECT ID FROM dpu_instance WHERE (ID = ?)")
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:157) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[spring-orm-3.1.4.RELEASE.jar:3.1.4.RELEASE]
        ... 37 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException:
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was72817 seconds ago.The last packet sent successfully to the server was 72817 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Error Code: 0
Call: SELECT ID FROM dpu_instance WHERE (ID = ?)
        bind => [2008]
Query: DoesExistQuery(referenceClass=DPUInstanceRecord sql="SELECT ID FROM dpu_instance WHERE (ID = ?)")
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:674) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.sessions.server.ServerSession.executeCall(ServerSession.java:570) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:250) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectRowForDoesExist(DatasourceCallQueryMechanism.java:736) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.queries.DoesExistQuery.executeDatabaseQuery(DoesExistQuery.java:241) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.checkForUnregisteredExistingObject(UnitOfWorkImpl.java:785) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.discoverAndPersistUnregisteredNewObjects(UnitOfWorkImpl.java:4194) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadeDiscoverAndPersistUnregisteredNewObjects(ObjectReferenceMapping.java:949) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.mappings.ObjectReferenceMapping.cascadeDiscoverAndPersistUnregisteredNewObjects(ObjectReferenceMapping.java:927) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.descriptors.ObjectBuilder.cascadeDiscoverAndPersistUnregisteredNewObjects(ObjectBuilder.java:2514) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.discoverAndPersistUnregisteredNewObjects(UnitOfWorkImpl.java:4207) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(RepeatableWriteUnitOfWork.java:305) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1516) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        ... 38 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was72817 seconds ago.The last packet sent successfully to the server was 72817 seconds ago, which  is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at sun.reflect.GeneratedConstructorAccessor215.newInstance(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_72]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1074) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3246) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1917) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1885) ~[mysql-connector-java-5.1.6.jar:na]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96) ~[commons-dbcp-1.4.jar:1.4]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeSelect(DatabaseAccessor.java:1007) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:642) ~[commons-app-1.4.1-SNAPSHOT.jar:na]
        ... 64 common frames omitted
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.7.0_72]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113) ~[na:1.7.0_72]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:159) ~[na:1.7.0_72]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.7.0_72]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.7.0_72]
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3227) ~[mysql-connector-java-5.1.6.jar:na]
        ... 73 common frames omitted
2014-11-20 07:20:47,784 [dpu: [INTLIB] PSP Extractor] WARN  exec:84 dpu:2008 c.c.m.x.odcs.backend.db.SQLDatabaseReconnectAspect - Database is down after 1 attempts.
        ... 73 common frames omitted
2014-11-20 07:20:47,784 [dpu: [INTLIB] PSP Extractor] WARN  exec:84 dpu:2008 c.c.m.x.odcs.backend.db.SQLDatabaseReconnectAspect - Database is down after 1 attempts.
2014-11-20 07:20:53,719 [taskScheduler-6] TRACE exec: dpu: c.c.mff.xrg.odcs.commons.app.scheduling.Schedule - onTimeCheck started
2014-11-20 07:21:06,113 [taskScheduler-2] DEBUG exec: dpu: cz.cuni.mff.xrg.odcs.backend.execution.Engine - >>> Entering checkJobs()
2014-11-20 07:32:46,991 [File notifier server] DEBUG exec: dpu: c.c.m.x.o.c.app.module.osgi.OSGIChangeManager - Udating DPU in: extractor_rdfa_distiller

</code></pre>

**Comment by tomas-knap** [comment]
Cannot be easily reproduced (branch which is not used, instance?), closed as won't fix
