### ISSUE TITLE
SQLDatabaseReconnectAspect

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#256]
SQLDatabaseReconnectAspect should react only in case of broken connection. 

In example bellow SQLDatabaseReconnectAspect  effectively block backend and frontend (Frontend was in RFC call).

```
2014-12-11 09:50:14,228 [RMI TCP Connection(4)-10.10.21.35] WARN  exec: dpu: c.c.m.x.o.b.d.SQLDatabaseReconnectAspect - Database is down after 7 attempts.
2014-12-11 09:50:16,231 [RMI TCP Connection(4)-10.10.21.35] WARN  exec: dpu: c.c.m.x.o.b.d.SQLDatabaseReconnectAspect - failureTolerant has caught exception
javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.
	at org.eclipse.persistence.internal.jpa.QueryImpl.throwNoResultException(QueryImpl.java:972) ~[classes/:na]
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:522) ~[classes/:na]
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310) ~[spring-orm-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at com.sun.proxy.$Proxy42.getSingleResult(Unknown Source) ~[na:na]
	at cz.cuni.mff.xrg.odcs.commons.app.dao.db.DbAccessReadBase.execute(DbAccessReadBase.java:133) ~[classes/:na]
	at cz.cuni.mff.xrg.odcs.commons.app.properties.DbRuntimePropertiesImpl.getByName(DbRuntimePropertiesImpl.java:39) ~[classes/:na]
	at cz.cuni.mff.xrg.odcs.commons.app.facade.RuntimePropertiesFacadeImpl.getByName(RuntimePropertiesFacadeImpl.java:30) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80) ~[spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.backend.db.SQLDatabaseReconnectAspect.failureTolerant(SQLDatabaseReconnectAspect.java:101) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at com.sun.proxy.$Proxy34.getByName(Unknown Source) [na:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.Engine.getLimitOfScheduledPipelines(Engine.java:168) [classes/:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.Engine.checkJobs(Engine.java:137) [classes/:na]
	at cz.cuni.mff.xrg.odcs.backend.execution.Engine.onApplicationEvent(Engine.java:241) [classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.backend.communication.CheckDatabaseServiceImpl.checkDatabase(CheckDatabaseServiceImpl.java:17) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.remoting.support.RemoteInvocationTraceInterceptor.invoke(RemoteInvocationTraceInterceptor.java:77) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) [spring-aop-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at com.sun.proxy.$Proxy36.checkDatabase(Unknown Source) [na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:205) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.remoting.support.DefaultRemoteInvocationExecutor.invoke(DefaultRemoteInvocationExecutor.java:38) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.remoting.rmi.RmiBasedExporter.invoke(RmiBasedExporter.java:73) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.remoting.rmi.RmiInvocationWrapper.invoke(RmiInvocationWrapper.java:72) [spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322) [na:1.7.0_45]
	at sun.rmi.transport.Transport$1.run(Transport.java:177) [na:1.7.0_45]
	at sun.rmi.transport.Transport$1.run(Transport.java:174) [na:1.7.0_45]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_45]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:173) [na:1.7.0_45]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556) [na:1.7.0_45]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811) [na:1.7.0_45]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670) [na:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

**Comment by tomas-knap** [comment]
@skodape Is this still valid or SQLDatabaseReconnectAspect was removed?
