### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Core#264]
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.112 sec <<< FAILURE! - in cz.cuni.mff.xrg.odcs.backend.scheduling.SchedulerTest
test3(cz.cuni.mff.xrg.odcs.backend.scheduling.SchedulerTest)  Time elapsed: 0.022 sec  <<< FAILURE!
java.lang.AssertionError: expected:<8> but was:<6>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at cz.cuni.mff.xrg.odcs.backend.scheduling.SchedulerTest.test3(SchedulerTest.java:131)

This test for particular order is not portable. 
For me the order of elements in the list is: 6, 9, 8
while expected order is: 8, 9, 6

**Comment by skodape** [comment]
The problem was with some build (from Netbeans on local host). 

Tests should now not fail if the ordering of elements is different. There is probably space for code improvement on used solution.
https://github.com/UnifiedViews/Core/commit/15d2f4241dd7b24f751b6ffdd5f0498e670931f7
