### ISSUE TITLE
Uncaught exception when trying to copy DPU on canvas

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#275]
Uncaught exception when trying to copy DPU on canvas - happened randomly
<pre><code>
2015-01-25 09:33:53,995 [http-nio-8080-exec-8] DEBUG org.eclipse.persistence.logging.sql - 2015-01-25 09:33:53.995--ServerSession(1938197431)--Connection(944042004)--SELECT ID FROM ppl_model WHERE (ID = ?)
        bind => [199]
2015-01-25 09:33:53,997 [http-nio-8080-exec-8] WARN  org.eclipse.persistence.logging.default - 2015-01-25 09:33:53.996--UnitOfWork(1476693048)--
2015-01-25 09:33:54,009 [http-nio-8080-exec-8] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: cz.cuni.mff.xrg.odcs.commons.app.pipeline.graph.Node@58ac5a01.
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.discoverUnregisteredNewObjects(RepeatableWriteUnitOfWork.java:310) ~[RepeatableWriteUnitOfWork.class:2.5.1.v20130918-f2b9fc5]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.calculateChanges(UnitOfWorkImpl.java:723) ~[UnitOfWorkImpl.class:2.5.1.v20130918-f2b9fc5]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1516) ~[UnitOfWorkImpl.class:2.5.1.v20130918-f2b9fc5]
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[RepeatableWriteUnitOfWork.class:2.5.1.v20130918-f2b9fc5]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[UnitOfWorkImpl.class:2.5.1.v20130918-f2b9fc5]
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[EntityTransactionImpl.class:2.5.1.v20130918-f2b9fc5]
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:512) ~[JpaTransactionManager.class:3.1.4.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754) ~[AbstractPlatformTransactionManager.class:3.1.4.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723) ~[AbstractPlatformTransactionManager.class:3.1.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387) ~[TransactionAspectSupport.class:3.1.4.RELEASE]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$afterReturning$org_springframework_transaction_aspectj_AbstractTransactionAspect$3$2a73e96c(AbstractTransactionAspect.aj:78) ~[AbstractTransactionAspect.class:3.1.4.RELEASE]
        at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacadeImpl.save(PipelineFacadeImpl.java:547) ~[PipelineFacadeImpl.class:na]
        at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319) ~[AopUtils.class:3.1.2.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196) ~[JdkDynamicAopProxy.class:3.1.2.RELEASE]
        at com.sun.proxy.$Proxy38.save(Unknown Source) ~[na:na]
        at cz.cuni.mff.xrg.odcs.frontend.auxiliaries.PipelineHelper.runPipeline(PipelineHelper.java:87) ~[PipelineHelper.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit.finishSavePipeline(PipelineEdit.java:1224) ~[PipelineEdit.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit.savePipeline(PipelineEdit.java:1194) ~[PipelineEdit.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.PipelineEdit$7.componentEvent(PipelineEdit.java:407) ~[PipelineEdit$7.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.fireEvent(PipelineCanvas.java:397) ~[PipelineCanvas.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.showDebugWindow(PipelineCanvas.java:517) ~[PipelineCanvas.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.access$500(PipelineCanvas.java:47) ~[PipelineCanvas.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas$1.onDebugRequested(PipelineCanvas.java:150) ~[PipelineCanvas$1.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[ServerRpcManager.class:7.3.7]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[ServerRpcManager.class:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:287) [ServerRpcHandler.class:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [ServerRpcHandler.class:7.3.7]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [UidlRequestHandler.class:7.3.7]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [SynchronizedRequestHandler.class:7.3.7]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [VaadinService.class:7.3.7]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [VaadinServlet.class:7.3.7]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:86) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [tomcat8-servlet-api-8.0.14.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
2015-01-25 09:33:54,013 [http-nio-8080-exec-8] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - < service (17981) in: 233 ms
2015-01-25 09:33:54,104 [http-nio-8080-exec-6] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - > service (17982)
2015-01-25 09:33:54,116 [http-nio-8080-exec-6] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - < service (17982) in: 12 ms
2015-01-25 09:33:54,527 [http-nio-8080-exec-10] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - > service (17983)
2015-01-25 09:33:54,527 [http-nio-8080-exec-10] TRACE c.c.mff.xrg.odcs.frontend.gui.views.PipelineEdit - refresh - 0
2015-01-25 09:33:54,527 [http-nio-8080-exec-10] TRACE c.c.m.x.odcs.commons.app.facade.PipelineFacadeImpl - createOpenEvent() ...

</code></pre>

**Comment by tomas-knap** [comment]
Problem is that certain object is saved and it references another object, which does not exist in the database. So there must be a cascade flag so that also the referenced object is saved
