### ISSUE TITLE
Unexpected error when backend is offline

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Core#286]
1. shut down backend
2. in frontend, create new pipeline
3. add some DPU, make the pipeline valid
4. click Save & Close & Debug
5. click Cancel
6. move some DPU around canvas.
7. unexpected error
```
11:06:57.925 [http-nio-0:0:0:0:0:0:0:1-8080-exec-10] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
java.lang.IllegalArgumentException: Node with supplied id was not found!
	at cz.cuni.mff.xrg.odcs.commons.app.pipeline.graph.PipelineGraph.moveNode(PipelineGraph.java:316) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.dpuMoved(PipelineCanvas.java:453) ~[PipelineCanvas.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas.access$400(PipelineCanvas.java:48) ~[PipelineCanvas.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.pipelinecanvas.PipelineCanvas$1.onDpuMoved(PipelineCanvas.java:144) ~[PipelineCanvas$1.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:287) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:86) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.50]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) [catalina.jar:7.0.50]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.50]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.50]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.50]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:7.0.50]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.50]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100) [catalina.jar:7.0.50]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953) [catalina.jar:7.0.50]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.50]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:409) [catalina.jar:7.0.50]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1044) [tomcat-coyote.jar:7.0.50]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote.jar:7.0.50]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721) [tomcat-coyote.jar:7.0.50]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679) [tomcat-coyote.jar:7.0.50]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

**Comment by tomas-knap** [comment]
Was not able to reproduce
