### ISSUE TITLE
Backend: internal error: ObjID already in use

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#339]
I installed UV on
Ubuntu 12.04.4 LTS
Java (Oracle) 1.8.0_40

and when I run backend, I get:
```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.remoting.rmi.RmiServiceExporter#1' defined in class path resource [backend-context.xml]: Invocation of init method failed; nested exception is java.rmi.server.ExportException: internal error: ObjID already in use
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
        at cz.cuni.mff.xrg.odcs.backend.AppEntry.initSpring(AppEntry.java:59)
        at cz.cuni.mff.xrg.odcs.backend.AppEntry.run(AppEntry.java:208)
        at cz.cuni.mff.xrg.odcs.backend.AppEntry.main(AppEntry.java:251)
Caused by: java.rmi.server.ExportException: internal error: ObjID already in use
        at sun.rmi.transport.ObjectTable.putTarget(ObjectTable.java:186)
        at sun.rmi.transport.Transport.exportObject(Transport.java:106)
        at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:260)
        at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
        at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
        at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:208)
        at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:152)
        at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:137)
        at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:203)
        at org.springframework.remoting.rmi.RmiServiceExporter.getRegistry(RmiServiceExporter.java:406)
        at org.springframework.remoting.rmi.RmiServiceExporter.getRegistry(RmiServiceExporter.java:377)
        at org.springframework.remoting.rmi.RmiServiceExporter.getRegistry(RmiServiceExporter.java:336)
        at org.springframework.remoting.rmi.RmiServiceExporter.prepare(RmiServiceExporter.java:268)
        at org.springframework.remoting.rmi.RmiServiceExporter.afterPropertiesSet(RmiServiceExporter.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
        ... 14 more
```

There are 2 RMI services in <code>backend/src/main/resources/backend-context.xml</code>
```
    <bean id="checkDatabaseService" class="cz.cuni.mff.xrg.odcs.backend.communication.CheckDatabaseServiceImpl"/>
    <bean class="org.springframework.remoting.rmi.RmiServiceExporter">
        <property name="serviceName" value="checkDatabase"/>
        <property name="service" ref="checkDatabaseService"/>
        <property name="serviceInterface" value="cz.cuni.mff.xrg.odcs.commons.app.communication.CheckDatabaseService"/>
        <property name="registryPort" value="${backend.port}"/>
    </bean>

    <bean id="heartbeatService" class="cz.cuni.mff.xrg.odcs.backend.communication.HeartbeatServiceImpl"/>
    <bean class="org.springframework.remoting.rmi.RmiServiceExporter">
        <property name="serviceName" value="heartbeat"/>
        <property name="service" ref="heartbeatService"/>
        <property name="serviceInterface" value="cz.cuni.mff.xrg.odcs.commons.app.communication.HeartbeatService"/>
        <property name="registryPort" value="${backend.port}"/>
    </bean>
```

When I disable any one of them, backend runs OK.
When I enable them both (default) I get the exception above.

**Comment by skrchnavy** [comment]
@jakubklimek is it reproducible in master or in develop or in a special branch?

**Comment by jakubklimek** [comment]
This is 76c989c09f2ec558e36e73276ab56764e4f868e9, current develop branch.

**Comment by skrchnavy** [comment]
@skodape isn't this cause that java8 hundles it diferently? The code is there for a year ( 2f81ea720cd52e737acf78e6b05548a4a5d6ec89 ) so it shall be observed sooner.

**Comment by jakubklimek** [comment]
It is not related to java8. We run backend on Java8 on Windows and Debian and it works OK. The difference is this:
Ubuntu:
```
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Looking for RMI registry at port '5010'
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Could not detect RMI registry - creating new one
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter prepare
INFO: Binding service 'checkDatabase' to RMI registry: RegistryImpl[UnicastServerRef [liveRef: [endpoint:[10.60.60.8:5010](local),objID:[0:0:0, 0]]]]
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Looking for RMI registry at port '5010'
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Could not detect RMI registry - creating new one
Mar 20, 2015 5:28:56 PM org.springframework.beans.factory.support.DefaultSingletonBeanRegistry destroySingletons
INFO: Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@55a561cf: defining beans [configuration,org.springframework.transaction.config.internalTransactionAspect,org.springframework.context.config.internalBeanConfigurerAspect,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.annotation.internalPersistenceAnnotationProcessor,org.springframework.aop.config.internalAutoProxyCreator,dataSource,emf,transactionManager,moduleFacade,watcher,userFacade,pipelineFacade,dpuFacade,logFacade,scheduleFacade,prefixFacade,runtimePropertiesFacade,DPUExplorer,dbPipeline,dbExecution,dbOpenEvent,dbTemplate,dbInstance,dbMessage,dbLogRead,dbSchedule,dbScheduleNotification,dbUserNotification,dbUser,dbNamespacePrefix,dbRuntimeProperties,dbAuthorizator,cz.cuni.mff.xrg.odcs.commons.app.dao.db.filter.BaseFilterTranslator#0,cz.cuni.mff.xrg.odcs.commons.app.resource.ResourceManager#0,cz.cuni.mff.xrg.odcs.commons.app.dataunit.DataUnitFactoryImpl#0,cz.cuni.mff.xrg.odcs.commons.app.rdf.RepositoryManager#0,cz.cuni.mff.xrg.odcs.commons.app.dataunit.relational.RelationalRepositoryManager#0,DBExecutionViewImpl,DBPipelineViewImpl,org.springframework.context.annotation.internalAsyncAnnotationProcessor,org.springframework.context.annotation.internalScheduledAnnotationProcessor,taskExecutor,taskScheduler,facadeAspect,moduleFacadeConfiguration,emailSender,checkDatabaseService,org.springframework.remoting.rmi.RmiServiceExporter#0,heartbeatService,org.springframework.remoting.rmi.RmiServiceExporter#1,engine,cz.cuni.mff.xrg.odcs.backend.execution.ExecutionSanitizer#0,dpuContext,cz.cuni.mff.xrg.odcs.backend.context.ContextFacade#0,cz.cuni.mff.xrg.odcs.backend.context.ContextCloser#0,cz.cuni.mff.xrg.odcs.backend.context.ContextCreator#0,cz.cuni.mff.xrg.odcs.backend.context.ContextDeleter#0,cz.cuni.mff.xrg.odcs.backend.context.ContextMerger#0,cz.cuni.mff.xrg.odcs.backend.context.ContextRestorer#0,cz.cuni.mff.xrg.odcs.backend.context.ContextSaver#0,pipelineExecutor,dpuExecutor,cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase#0,scheduler,cz.cuni.mff.xrg.odcs.backend.pruning.Log#0,cz.cuni.mff.xrg.odcs.backend.logback.SqlAppenderImpl#0,cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIChangeManager#0,checkDataUnits,annotationsInput,annotationsOutput,DPUPreExecutorContextPreparator,configurator,contextSaver,restarter,conflictLock,cleanUp,conflictUnLock,dailyReport,dailyReportEmailBuilder,instantReport,instantReportEmailBuilder,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor]; root of factory hierarchy
Mar 20, 2015 5:28:56 PM org.springframework.remoting.rmi.RmiServiceExporter destroy
INFO: Unbinding RMI service 'checkDatabase' from registry at port '5010'
2015-03-20 17:28:56,063 [main] TRACE exec: dpu: c.c.m.x.o.c.a.m.i.FileNotifierClient - Stopping FileNotifierServer ...
2015-03-20 17:28:56,064 [File notifier server] TRACE exec: dpu: c.c.m.x.o.c.a.m.i.FileNotifierClient - DPU's change watcher has been interrupted.
2015-03-20 17:28:56,064 [main] TRACE exec: dpu: c.c.m.x.o.c.a.m.i.FileNotifierClient - FileNotifierServer has been stopped.
Mar 20, 2015 5:28:56 PM org.springframework.orm.jpa.AbstractEntityManagerFactoryBean destroy
INFO: Closing JPA EntityManagerFactory for persistence unit 'odcs'
Mar 20, 2015 5:28:56 PM org.springframework.scheduling.concurrent.ExecutorConfigurationSupport shutdown
INFO: Shutting down ExecutorService 'taskScheduler'
Mar 20, 2015 5:28:56 PM org.springframework.scheduling.concurrent.ExecutorConfigurationSupport shutdown
INFO: Shutting down ExecutorService
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.remoting.rmi.RmiServiceExporter#1' defined in class path resource [backend-context.xml]: Invocation of init method failed; nested exception is java.rmi.server.ExportException: internal error: ObjID already in use
```

Windows (and Debian I guess):
```
Bře 20, 2015 5:32:05 ODP. org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Looking for RMI registry at port '5010'
Bře 20, 2015 5:32:06 ODP. org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Could not detect RMI registry - creating new one
Bře 20, 2015 5:32:06 ODP. org.springframework.remoting.rmi.RmiServiceExporter prepare
INFO: Binding service 'checkDatabase' to RMI registry: RegistryImpl[UnicastServerRef [liveRef: [endpoint:[10.10.21.192:5010](local),objID:[0:0:0, 0]]]]
Bře 20, 2015 5:32:06 ODP. org.springframework.remoting.rmi.RmiServiceExporter getRegistry
INFO: Looking for RMI registry at port '5010'
Bře 20, 2015 5:32:06 ODP. org.springframework.remoting.rmi.RmiServiceExporter prepare
INFO: Binding service 'heartbeat' to RMI registry: RegistryImpl_Stub[UnicastRef [liveRef: [endpoint:[10.10.21.192:5010](remote),objID:[0:0:0, 0]]]]
```

so this is clearly an issue with RMI creating the second registry when one is already there.
The question is what causes it.

**Comment by tomas-knap** [comment]
And is there a difference in the java 8 version on Windows/Debian (where it works) and on Ubuntu?

**Comment by jakubklimek** [comment]
In addition, when I set the two services for different ports (5011 and 5012) it works.
Yes, there is a difference, this is java 8 update 40, we run on update 25 - I will upgrade and report back

**Comment by jakubklimek** [comment]
OK, runs with java 8 update 40 on debian.

**Comment by jakubklimek** [comment]
I think we may be on a path to the problem... long story short IPv4/IPv6
Backend starts and creates the first registry. When I run netstat, I see that port 5010 is open, but on tcp6.
Then it searches for the registry again for the second service, it looks at 127.0.0.1:5010 - tcp. It is not there because it is listening on tcp6. So it tries to create it, but it already exists -> exception.

**Comment by tomas-knap** [comment]
I think we cannot do much with this apart from defining two different ports for the services (just to be sure). I would suggest to close for now. If we experience further problems regarding this even in other configurations, two different ports should be defined.

**Comment by jakubklimek** [comment]
Have you read my last comment? It is clear that
1) it is an urgent bug / blocker - it is supposed to be a COMSODE UV instance
2) even the two ports don't help because they are opened on tcp6 whereas frontend tries to connect to tcp
3) We spent a non-trivial time debugging this and pinpointed the problem so that it can be fixed ASAP so that we can continue with the installation.

So closing this issue without fixing it is not an option here.

**Comment by tomas-knap** [comment]
Motivation: This happens on one ODN instance, where ODN should be installed on Ubuntu. 

To solve the bug:
* Install virtual image of Ubuntu version as described above, Java as above (but the version of Java should not be the cause of the problem, as it runs on Debian with Java8), test it to check you can reproduce. 
* creating of RMI services and its bindings to ports must properly work with IPv6, or IPv4 must be enforced. 
* Test that it works correctly also on Debian

**Comment by mkl-eea-sk** [comment]
It may be interesting to set debug log level for spring, as relevant 
exception is logged in this chunk of code:
```
         synchronized (LocateRegistry.class) {
             try {
                 // Retrieve existing registry.
                 Registry reg = LocateRegistry.getRegistry(registryPort);
                 testRegistry(reg);
                 return reg;
             }
             catch (RemoteException ex) {
                 logger.debug("RMI registry access threw exception", ex);
                 logger.info("Could not detect RMI registry - creating 
new one");
                 // Assume no registry found -> create new one.
                 return LocateRegistry.createRegistry(registryPort);
             }
         }
```
Since it is synchronized, it must be that Java implementation of 
LocateRegistry does not return the already created one when asked for it.

**Comment by skrchnavy** [comment]
ODN default platform is debian wheezy

**Comment by mkl-eea-sk** [comment]
If it is IPv4/IPv6 problem, define registryHost for RmiServiceExporter 
bean to hardcoded value 127.0.0.1.

**Comment by martinnec** [comment]
This problem is related to one of the official instances of ODN so it MUST be fixed. The solution is suggested above. The justification above that ODN is supported only on Debian is not acceptable. All this discussion showed that it is a bug and it is only a coincidence that it did not showed up on Debian.

**Comment by tomas-knap** [comment]
So it will be solved after 31.3., when UV Release 2.0 is done. After 31.3. @skrchnavy  should allocate the issue.

**Comment by jakubklimek** [comment]
Wouldn't it make more sense to fix this now so that we can deploy release
2.0 at the customer?

**Comment by tomas-knap** [comment]
The problem is that there is no developer who can fix it now on EEA site, because of preparing release 2.0

**Comment by tomas-knap** [comment]
@skrchnavy Do we solve this issue? It seems to be a bug, which does not appear on debian wheezy

**Comment by skrchnavy** [comment]
at debian wheezy this was not observed until now.
