### ISSUE TITLE
Branch sso_fixes: Cannot log in with user having role 2 (user)

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Core#340]
Branch sso_fixes, 6b0ead485bdd048a4e3d2ea0e8aa463cd4781c9f 

In general the problem is that I cannot log in with user having role user (role 2): 

To reproduce:
1) Use mysql, fresh db. Db initialized with schema.sql, then data.sql. 
2) Make sure that table "usr_user_role" contains VALUES (1,1);
3) Open frontend
4) try to log as admin (admin/test) in frontend
5) everything works as expected

6) Make sure that table "usr_user_role" contains VALUES (1,1),(1,2);
7) Open frontend
8) try to log as admin (admin/test) in frontend
9) error occurs in frontend.log

```
2015-03-20 19:41:01,563 [http-bio-8080-exec-1] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: No conversion value provided for the value [2] in field [null].
Mapping: org.eclipse.persistence.mappings.DirectCollectionMapping[roles]
Descriptor: RelationalDescriptor(cz.cuni.mff.xrg.odcs.commons.app.user.User --> [DatabaseTable(usr_user)])
	at org.eclipse.persistence.exceptions.DescriptorException.noFieldValueConversionToAttributeValueProvided(DescriptorException.java:1066) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.ObjectTypeConverter.convertDataValueToObjectValue(ObjectTypeConverter.java:225) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.EnumTypeConverter.convertDataValueToObjectValue(EnumTypeConverter.java:141) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.buildObject(DataReadQuery.java:184) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:225) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:129) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:116) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.buildDelegate(IndirectSet.java:211) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.getDelegate(IndirectSet.java:375) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.toArray(IndirectSet.java:557) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at java.util.ArrayList.<init>(ArrayList.java:151) ~[na:1.7.0_21]
	at cz.cuni.mff.xrg.odcs.commons.app.user.User.getAuthorities(User.java:260) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.createSuccessAuthentication(AbstractUserDetailsAuthenticationProvider.java:196) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:175) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService.login(AuthenticationService.java:97) ~[AuthenticationService.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.login(Login.java:127) ~[Login.class:na]
....
```

**Comment by tomas-knap** [comment]
It seems that the value (1,2) in usr_user_role is out of range. Because if I add new user via GUI having admin and user roles, it creates (1,0), (1,1) rows in usr_user_role. Similarly, if I add new user via GUI having just user role, it creates (1,0). So it seems that User role has id 0 and not 2. But when checking table role, it contains: 1 Administrator, 2 User. So it is strange.

**Comment by peterklimo** [comment]
this is most probably problem in the mysql version of initialization
script, we used mainly pgsql, I have to test it with mysql

**Comment by tomas-knap** [comment]
Yes, please test, thanks!

**Comment by peterklimo** [comment]
mysql db script fixed (commit 9294797)

**Comment by tomas-knap** [comment]
Committed to wrong branch? It should be in feature_sso branch.

**Comment by peterklimo** [comment]
cherrypicked to feature_sso

**Comment by tomas-knap** [comment]
Still having the problem. When starting frontend, I got: 

```
2015-03-27 09:52:13,236 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2015-03-27 09:52:13.235--ServerSession(1958644902)--Connection(1110042921)--SELECT ID AS a1, full_name AS a2, u_password AS a3, table_rows AS a4, USERNAME AS a5, email_id AS a6 FROM usr_user WHERE (USERNAME = ?) LIMIT ?, ?
	bind => [admin, 0, 1]
2015-03-27 09:52:13,605 [http-bio-8080-exec-10] DEBUG org.eclipse.persistence.logging.sql - 2015-03-27 09:52:13.605--ServerSession(1958644902)--Connection(807102635)--SELECT t0.role_id FROM usr_user_role t0 WHERE (t0.user_id = ?)
	bind => [1]
2015-03-27 09:52:13,615 [http-bio-8080-exec-10] WARN  org.eclipse.persistence.logging.default - 2015-03-27 09:52:13.615--UnitOfWork(269033343)--
2015-03-27 09:52:13,623 [http-bio-8080-exec-10] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: No conversion value provided for the value [2] in field [null].
Mapping: org.eclipse.persistence.mappings.DirectCollectionMapping[roles]
Descriptor: RelationalDescriptor(cz.cuni.mff.xrg.odcs.commons.app.user.User --> [DatabaseTable(usr_user)])
	at org.eclipse.persistence.exceptions.DescriptorException.noFieldValueConversionToAttributeValueProvided(DescriptorException.java:1066) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.ObjectTypeConverter.convertDataValueToObjectValue(ObjectTypeConverter.java:225) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.EnumTypeConverter.convertDataValueToObjectValue(EnumTypeConverter.java:141) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.buildObject(DataReadQuery.java:184) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:225) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:129) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:116) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.buildDelegate(IndirectSet.java:211) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.getDelegate(IndirectSet.java:375) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.toArray(IndirectSet.java:557) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at java.util.ArrayList.<init>(ArrayList.java:151) ~[na:1.7.0_21]
	at cz.cuni.mff.xrg.odcs.commons.app.user.User.getAuthorities(User.java:260) ~[commons-app-1.6.0-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.createSuccessAuthentication(AbstractUserDetailsAuthenticationProvider.java:196) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:175) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService.login(AuthenticationService.java:97) ~[AuthenticationService.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.login(Login.java:127) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.access$000(Login.java:40) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login$2.buttonClick(Login.java:112) ~[Login$2.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_21]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_21]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_21]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_21]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.fireClick(Button.java:380) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.click(Button.java:369) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:548) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:233) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleActions(ActionManager.java:216) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.UI.changeVariables(UI.java:361) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) [catalina.jar:7.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) [catalina.jar:7.0.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) [catalina.jar:7.0.39]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947) [catalina.jar:7.0.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) [catalina.jar:7.0.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.39]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009) [tomcat-coyote.jar:7.0.39]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) [tomcat-coyote.jar:7.0.39]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312) [tomcat-coyote.jar:7.0.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
2015-03-27 09:52:13,627 [http-bio-8080-exec-10] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - < service (5) in: 399 ms
2015-03-27 09:52:15,216 [http-bio-8080-exec-10] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - > service (6)
2015-03-27 09:52:15,218 [http-bio-8080-exec-10] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - < service (6) in: 2 ms

```

**Comment by tomas-knap** [comment]
The root of the problem is probably: 

It seems that the value "2" for user role in table usr_user_role is out of range. Because if I add new user via GUI having admin and user roles, it creates (1,0), (1,1) rows in usr_user_role. Similarly, if I add new user via GUI having just user role, it creates (1,0) in usr_user_role. **So it seems that user role has id 0 and not 2** if created via GUI (manage users). 

Nevertheless, when checking table roles, it contains: 1 Administrator, 2 User. So ID for role "user" is sometimes 0, sometimes 2.

**Comment by tomas-knap** [comment]
So the commit https://github.com/UnifiedViews/Core/commit/92947976009cec03af16c1b2060b9d366b4e7737 does not fix this issue.

**Comment by tomas-knap** [comment]
There was a problem with using older version of commons-app during tests.
