### ISSUE TITLE
Frontend: uncaught exception: missing config property ownership.type

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#355]
When I try to login to frontend, I get Uncaught exception without any explanation.

Then I have to search through logs to get this error which I don't know how to solve (related to https://github.com/UnifiedViews/Core/issues/352):
```
09:30:21.073 [http-nio-8080-exec-6] ERROR c.c.m.x.o.f.AppEntry - Uncaught exception
cz.cuni.mff.xrg.odcs.commons.app.conf.MissingConfigPropertyException: Config is missing property: ownership.type.
	at cz.cuni.mff.xrg.odcs.commons.app.conf.AppConfig.getString(AppConfig.java:118) ~[commons-app-2.1.0-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.commons.app.auth.PasswordAuthenticationProvider.retrieveUser(PasswordAuthenticationProvider.java:91) ~[commons-app-2.1.0-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:132) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService.login(AuthenticationService.java:97) ~[AuthenticationService.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.login(Login.java:127) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.access$000(Login.java:40) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login$2.buttonClick(Login.java:112) ~[Login$2.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_40]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.fireClick(Button.java:380) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.click(Button.java:369) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:548) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:233) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleActions(ActionManager.java:216) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.UI.changeVariables(UI.java:361) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.21]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.21]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.21]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.21]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.21]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.21]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.21]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.21]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.21]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.21]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-coyote.jar:8.0.21]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.21]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517) [tomcat-coyote.jar:8.0.21]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474) [tomcat-coyote.jar:8.0.21]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_40]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.21]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_40]
```

**Comment by eea01** [comment]
The same as #352.

**Comment by jakubklimek** [comment]
@eea01 This is not the same as #352 - the issue here is that when a property is missing, frontend crashes with "Unexpected error" and I need to go through logs to find out what it is. It is
1) different behavior from #352 where frontend does not start at all and the exception is visible directly
2) Unacceptable to crash this way. An appropriate error messsage must be shown in these cases, saying config should be modified according to a sample is not enough.

**Comment by skrchnavy** [comment]
Based on the changes in https://github.com/UnifiedViews/Core/pull/382/files#diff-470740c3363ebb5c2d69b53721e42c37L121 , property was removed from configuration file so I think we can close this issue now as invalid.

To handle changers in configurations there is defined issue #303.

@jakubklimek please comment.

**Comment by tomas-knap** [comment]
Closed as the problematic property was removed from UV
