### ISSUE TITLE
Cannot replace DPU

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#367]
After update to current develop I cannot replace any DPU. When I do, I get Unexpected error and in frontend log I see:
```
2015-04-22 14:30:54,805 [http-nio-8080-exec-16] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.IllegalArgumentException: Filter target must be a collection or array type, but was E-DatasetMetadata
        at org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler.filter(DefaultMethodSecurityExpressionHandler.java:144) ~[DefaultMethodSecurityExpressionHandler.class:3.1.4.RELEASE]
        at org.springframework.security.access.expression.method.ExpressionBasedPostInvocationAdvice.after(ExpressionBasedPostInvocationAdvice.java:41) ~[ExpressionBasedPostInvocationAdvice.class:3.1.4.RELEASE]
        at org.springframework.security.access.prepost.PostInvocationAdviceProvider.decide(PostInvocationAdviceProvider.java:38) ~[PostInvocationAdviceProvider.class:3.1.4.RELEASE]
        at org.springframework.security.access.intercept.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:73) ~[AfterInvocationProviderManager.class:3.1.4.RELEASE]
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:282) ~[AbstractSecurityInterceptor.class:3.1.4.RELEASE]
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:68) ~[MethodSecurityInterceptor.class:3.1.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[ReflectiveMethodInvocation.class:3.1.2.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[JdkDynamicAopProxy.class:3.1.2.RELEASE]
        at com.sun.proxy.$Proxy144.getTemplate(Unknown Source) ~[na:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploaded(DPUPresenterImpl.java:240) ~[DPUPresenterImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUPresenterImpl.dpuUploadedEventHandler(DPUPresenterImpl.java:295) ~[DPUPresenterImpl.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.views.dpu.DPUViewImpl$13.uploadSucceeded(DPUViewImpl.java:653) ~[DPUViewImpl$13.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareUploadSucceededWrapper.uploadSucceeded(AuthAwareUploadSucceededWrapper.java:48) ~[AuthAwareUploadSucceededWrapper.class:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[ListenerMethod.class:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[EventRouter.class:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[EventRouter.class:7.3.7]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) ~[AbstractClientConnector.class:7.3.7]
        at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:888) ~[Upload.class:7.3.7]
        at com.vaadin.ui.Upload$2.streamingFinished(Upload.java:1150) ~[Upload$2.class:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:597) [FileUploadHandler.class:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:453) [FileUploadHandler.class:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:403) [FileUploadHandler.class:7.3.7]
        at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:285) [FileUploadHandler.class:7.3.7]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [VaadinService.class:7.3.7]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [VaadinServlet.class:7.3.7]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [tomcat8-servlet-api-8.0.14.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat8-websocket-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by skrchnavy** [comment]
@eea03 please check

**Comment by eea03** [comment]
OK, this was wrong annotation on facade method, should work now; I tested replace and import new DPU, both working

**Comment by jakubklimek** [comment]
Works for me
