### ISSUE TITLE
Frontend throws exception when started without SSO configured

### ISSUE THREAD

**Issue by cmader** [UnifiedViews/Core#383]
11:47:59.307 [pool-2-thread-1] ERROR o.s.w.c.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestSingleLogoutFilter' defined in ServletContext resource [/WEB-INF/classes/cas-context-security.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472) ~[spring-context-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204) ~[spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47) [spring-web-3.0.7.RELEASE.jar:3.0.7.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4779) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:649) [tomcat-catalina-7.0.26.jar:7.0.26]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1581) [tomcat-catalina-7.0.26.jar:7.0.26]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	... 27 common frames omitted
Caused by: java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.util.Assert.isTrue(Assert.java:65) ~[spring-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.<init>(LogoutFilter.java:73) ~[spring-security-web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_80]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_80]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_80]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_80]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	... 29 common frames omitted
May 08, 2015 11:47:59 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestSingleLogoutFilter' defined in ServletContext resource [/WEB-INF/classes/cas-context-security.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1035)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:939)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:607)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:925)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:472)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4779)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:895)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:871)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:615)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:649)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1581)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springframework.security.web.authentication.logout.LogoutFilter]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:162)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:280)
	... 27 more
Caused by: java.lang.IllegalArgumentException: ${cas.logout.url} isn't a valid redirect URL
	at org.springframework.util.Assert.isTrue(Assert.java:65)
	at org.springframework.security.web.authentication.logout.LogoutFilter.<init>(LogoutFilter.java:73)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 29 more

May 08, 2015 11:47:59 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
May 08, 2015 11:47:59 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/unifiedviews] startup failed due to previous errors
May 08, 2015 11:47:59 AM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
May 08, 2015 11:47:59 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/unifiedviews] appears to have started a thread named [State Saver] but has failed to stop it. This is very likely to create a memory leak.
May 08, 2015 11:47:59 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-127.0.0.1-28080"]
May 08, 2015 11:47:59 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-28009"]
May 08, 2015 11:47:59 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 28756 ms
May 08, 2015 11:47:59 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap$Snapshot$ValueCollection.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1587)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	at org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap$Snapshot.values(CopyOnWriteIdentityMap.java:456)
	at org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap.values(CopyOnWriteIdentityMap.java:360)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.removeAllServiceListeners(ServiceRegistry.java:746)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.close(BundleContextImpl.java:84)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.close(InternalSystemBundle.java:162)
	at org.eclipse.osgi.framework.internal.core.Framework.close(Framework.java:607)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:261)
	at java.lang.Thread.run(Thread.java:745)

May 08, 2015 11:47:59 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.eclipse.core.runtime.internal.adaptor.EclipseAdaptorMsg.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1587)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.handleRuntimeError(EclipseErrorHandler.java:77)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.handleRuntimeError(BaseAdaptor.java:415)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:264)
	at java.lang.Thread.run(Thread.java:745)

java.lang.NoClassDefFoundError: org/eclipse/osgi/framework/eventmgr/CopyOnWriteIdentityMap$Snapshot$ValueCollection
	at org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap$Snapshot.values(CopyOnWriteIdentityMap.java:456)
	at org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap.values(CopyOnWriteIdentityMap.java:360)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.removeAllServiceListeners(ServiceRegistry.java:746)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.close(BundleContextImpl.java:84)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle.close(InternalSystemBundle.java:162)
	at org.eclipse.osgi.framework.internal.core.Framework.close(Framework.java:607)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:261)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.osgi.framework.eventmgr.CopyOnWriteIdentityMap$Snapshot$ValueCollection
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1701)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	... 8 more
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/internal/adaptor/EclipseAdaptorMsg
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.handleRuntimeError(EclipseErrorHandler.java:77)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.handleRuntimeError(BaseAdaptor.java:415)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:264)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.internal.adaptor.EclipseAdaptorMsg
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1701)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	... 4 more
May 08, 2015 11:47:59 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load java.lang.VirtualMachineError.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1587)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.isFatalException(EclipseErrorHandler.java:62)
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.handleRuntimeError(EclipseErrorHandler.java:96)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.handleRuntimeError(BaseAdaptor.java:415)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:264)
	at java.lang.Thread.run(Thread.java:745)

May 08, 2015 11:47:59 AM org.apache.catalina.loader.WebappClassLoader loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load java.lang.ThreadDeath.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1587)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1546)
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.isFatalException(EclipseErrorHandler.java:65)
	at org.eclipse.core.runtime.internal.adaptor.EclipseErrorHandler.handleRuntimeError(EclipseErrorHandler.java:96)
	at org.eclipse.osgi.baseadaptor.BaseAdaptor.handleRuntimeError(BaseAdaptor.java:415)
	at org.eclipse.osgi.framework.internal.core.InternalSystemBundle$1.run(InternalSystemBundle.java:264)
	at java.lang.Thread.run(Thread.java:745)

**Comment by skrchnavy** [comment]
@cmader please provide commit number (or branch at least) to be able to reproduce the issue. thanks.

**Comment by skrchnavy** [comment]
@cmader please inform how was UV installed? From sources or from debian package? If from deb package, then this is reported as UnifiedViews/Packages#30

**Comment by skrchnavy** [comment]
closed, expected this is same issue as  UnifiedViews/Packages#30
