### ISSUE TITLE
eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o

### ISSUE THREAD

**Issue by jindrichmynarz** [UnifiedViews/Core#389]
Moved from comsode-uv-plugins/t-geonamesOrgToTriples#2 because @mkl-eea-sk identified it as an issue of UnifiedViews/Core.

When I run the [t-geonamesOrgToTriples](https://github.com/comsode-uv-plugins/t-geonamesOrgToTriples) using ODN 1.0.1 installed from the odn-simple Debian package I get the following error:

```
Failed to prepare Context for DPURecord because of exception: cz.cuni.mff.xrg.odcs.backend.context.ContextException: Failed to create DataUnit.
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:54)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.bind(DPUExecutor.java:147)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.execute(Executor.java:316)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:429)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.getSingleObject(AbstractWritableMetadataDataUnit.java:513)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.access$000(AbstractWritableMetadataDataUnit.java:44)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit$4.execute(AbstractWritableMetadataDataUnit.java:329)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:77)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:41)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.load(AbstractWritableMetadataDataUnit.java:309)
at cz.cuni.mff.xrg.odcs.backend.context.DataUnitManager.reload(DataUnitManager.java:207)
at cz.cuni.mff.xrg.odcs.backend.context.ContextRestorer.restore(ContextRestorer.java:28)
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:52)
```

What does `eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o` mean?

**Comment by mkl-eea-sk** [comment]
First of all, is it still in 1.0.3? With latest https://github.com/comsode-uv-plugins/t-geonamesOrgToTriples? If so, I will try to reproduce.

**Comment by jindrichmynarz** [comment]
I cannot check, because upgrade to 1.0.3 seems broken (OpenDataNode/open-data-node#158).

**Comment by jindrichmynarz** [comment]
Using ODN 1.0.3 I can no longer reproduce this issue. Closing it for now.
