### ISSUE TITLE
Fronted: after update to latest develop, I get exception and cannot login

### ISSUE THREAD

**Issue by jakubklimek** [UnifiedViews/Core#407]
After update to latest develop 3a5bfb90c94d2b599a8a7cc5ca3ed82e41dc9197 I get "unexpected error" when trying to login and in the log, there is:
```
2015-06-07 16:28:21,128 [http-apr-8080-exec-8] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: No conversion value provided for the value [2] in field [null].
Mapping: org.eclipse.persistence.mappings.DirectCollectionMapping[roles]
Descriptor: RelationalDescriptor(cz.cuni.mff.xrg.odcs.commons.app.user.User --> [DatabaseTable(usr_user)])
	at org.eclipse.persistence.exceptions.DescriptorException.noFieldValueConversionToAttributeValueProvided(DescriptorException.java:1066) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.ObjectTypeConverter.convertDataValueToObjectValue(ObjectTypeConverter.java:225) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.mappings.converters.EnumTypeConverter.convertDataValueToObjectValue(EnumTypeConverter.java:141) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.buildObject(DataReadQuery.java:184) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeNonCursor(DataReadQuery.java:225) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.executeDatabaseQuery(DataReadQuery.java:152) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DataReadQuery.execute(DataReadQuery.java:137) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:129) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.QueryBasedValueHolder.instantiate(QueryBasedValueHolder.java:116) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiateImpl(UnitOfWorkValueHolder.java:173) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.instantiate(UnitOfWorkValueHolder.java:234) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:89) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.buildDelegate(IndirectSet.java:211) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.getDelegate(IndirectSet.java:375) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.eclipse.persistence.indirection.IndirectSet.toArray(IndirectSet.java:557) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at java.util.ArrayList.<init>(ArrayList.java:177) ~[na:1.8.0_40]
	at cz.cuni.mff.xrg.odcs.commons.app.user.User.getAuthorities(User.java:260) ~[commons-app-2.0.0-SNAPSHOT.jar:na]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.createSuccessAuthentication(AbstractUserDetailsAuthenticationProvider.java:196) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:175) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:156) ~[spring-security-core-3.1.4.RELEASE.jar:3.1.4.RELEASE]
	at cz.cuni.mff.xrg.odcs.frontend.auth.AuthenticationService.login(AuthenticationService.java:97) ~[AuthenticationService.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.login(Login.java:127) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login.access$000(Login.java:40) ~[Login.class:na]
	at cz.cuni.mff.xrg.odcs.frontend.gui.views.Login$2.buttonClick(Login.java:112) ~[Login$2.class:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.fireClick(Button.java:380) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button.click(Button.java:369) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.Button$ClickShortcut.handleAction(Button.java:548) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:238) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ConnectorActionManager.handleAction(ConnectorActionManager.java:81) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:233) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.event.ActionManager.handleActions(ActionManager.java:216) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.ui.UI.changeVariables(UI.java:361) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:485) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:301) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.20]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.20]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.20]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.20]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.20]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.20]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.20]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.20]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.20]
	at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:285) [tomcat-coyote.jar:8.0.20]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2439) [tomcat-coyote.jar:8.0.20]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2428) [tomcat-coyote.jar:8.0.20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by jakubklimek** [comment]
I tried this even with a clean and freshly initialized database

**Comment by eea03** [comment]
Are you using Postgres or MySQL? I have never encountered this problem with Postgres, however, latest develop probably has not been tested with MySQL

**Comment by tomas-knap** [comment]
Kuba is using MySQL

**Comment by tomas-knap** [comment]
It is strange, that the problem is in 2.0.0-SNAPSHOT, although Kuba was testing latest develop.

**Comment by tomas-knap** [comment]
It seems that tomcat did not replace uv.war properly, so accidentally older version was used. Will update.
