### ISSUE TITLE
column "short_message" in table exec_record is too short

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#415]
too short https://github.com/UnifiedViews/Core/blob/master/db/postgresql/schema.sql#L139

uv gui log
```
Database is down after 2 attempts.
```

uv gui log 2
```
failureTolerant has caught exception

Stack trace:
org.springframework.transaction.TransactionSystemException Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(128)
Error Code: 0
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
	bind => [86, , Nepodarilo sa vytvoriť zdroj a datastore Nezamestnani absolventi strednych skol SR - API rozhranie pre databázovú tabuľku NEZ..., 2015-06-15 13:37:45.051, 3, 35, 9]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@2fd)
   at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
   at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
   at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
   at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:387)
   at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$afterReturning$org_springframework_transaction_aspectj_AbstractTransactionAspect$3$2a73e96c(AbstractTransactionAspect.aj:78)
   at cz.cuni.mff.xrg.odcs.commons.app.facade.DPUFacadeImpl.save(DPUFacadeImpl.java:279)
   at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
   at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
   at cz.cuni.mff.xrg.odcs.backend.db.SQLDatabaseReconnectAspect.failureTolerant(SQLDatabaseReconnectAspect.java:102)
   at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
   at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
   at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
   at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
   at com.sun.proxy.$Proxy29.save(Unknown Source)
   at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onDPUEvent(EventListenerDatabase.java:29)
   at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:46)
   at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:292)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:277)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:270)
   at eu.unifiedviews.plugins.loader.relationaltockan.RelationalToCkan.innerExecute(RelationalToCkan.java:205)
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
javax.persistence.RollbackException Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(128)
Error Code: 0
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
	bind => [86, , Nepodarilo sa vytvoriť zdroj a datastore Nezamestnani absolventi strednych skol SR - API rozhranie pre databázovú tabuľku NEZ..., 2015-06-15 13:37:45.051, 3, 35, 9]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@2fd)
   ... 37 common frames omitted   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
org.eclipse.persistence.exceptions.DatabaseException 
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(128)
Error Code: 0
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
	bind => [86, , Nepodarilo sa vytvoriť zdroj a datastore Nezamestnani absolventi strednych skol SR - API rozhranie pre databázovú tabuľku NEZ..., 2015-06-15 13:37:45.051, 3, 35, 9]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@2fd)
   ... 38 common frames omitted   at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$afterReturning$org_springframework_transaction_aspectj_AbstractTransactionAspect$3$2a73e96c(AbstractTransactionAspect.aj:78)
   at cz.cuni.mff.xrg.odcs.commons.app.facade.DPUFacadeImpl.save(DPUFacadeImpl.java:279)
   at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
   at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
   at cz.cuni.mff.xrg.odcs.backend.db.SQLDatabaseReconnectAspect.failureTolerant(SQLDatabaseReconnectAspect.java:102)
   at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
   at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
   at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
   at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
   at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
   at com.sun.proxy.$Proxy29.save(Unknown Source)
   at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onDPUEvent(EventListenerDatabase.java:29)
   at cz.cuni.mff.xrg.odcs.backend.EventListenerDatabase.onApplicationEvent(EventListenerDatabase.java:46)
   at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:292)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:277)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:270)
   at eu.unifiedviews.plugins.loader.relationaltockan.RelationalToCkan.innerExecute(RelationalToCkan.java:205)
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
org.postgresql.util.PSQLException ERROR: value too long for type character varying(128)
   ... 69 common frames omitted   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:292)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:277)
   at cz.cuni.mff.xrg.odcs.backend.context.Context.sendMessage(Context.java:270)
   at eu.unifiedviews.plugins.loader.relationaltockan.RelationalToCkan.innerExecute(RelationalToCkan.java:205)
   at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
   at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
   at java.lang.Thread.run(Thread.java:745)
```

backend.log
```
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(128)
Error Code: 0
Call: INSERT INTO exec_record (ID, full_message, short_message, r_time, r_type, dpu_id, execution_id) VALUES (?, ?, ?, ?, ?, ?, ?)
        bind => [36, , Nepodarilo sa vytvori? zdroj a datastore Nezamestnan? basolventi stredn?ch ?k?l SR - API rozhranie pre datab?zov? tabu?ku NEZ..., 2015-06-15 13:23:48.747, 3, 35, 4]
Query: InsertObjectQuery(cz.cuni.mff.xrg.odcs.commons.app.execution.message.MessageRecord@2cb)
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1611) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:898) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:962) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:631) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:558) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:1991) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:298) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:377) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:165) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:180) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:489) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:80) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:90) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:301) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:58) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:899) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:798) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:108) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:85) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1793) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1775) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1726) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:226) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:125) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4196) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1441) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1531) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.commitRootUnitOfWork(RepeatableWriteUnitOfWork.java:277) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitAndResume(UnitOfWorkImpl.java:1169) ~[commons-app-2.0.3.jar:na]
        at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:132) ~[commons-app-2.0.3.jar:na]
        ... 38 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(128)
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) ~[postgresql-9.3-1102-jdbc41.jar:na]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890) ~[commons-app-2.0.3.jar:na]
        ... 69 common frames omitted
```

**Comment by skrchnavy** [comment]
I don't expect column will be extended, short message shall be truncated before writing into DB (proposed is also to use ```...``` at the end of message when truncated)

**Comment by tomas-knap** [comment]
As Sveto wrote

**Comment by pgo-eea-sk** [comment]
Short message was cutted to 128 characters. Commit 518b2fcd91a49c5e85a34ce5ef283c6d3f717075

**Comment by skrchnavy** [comment]
pull request #417 created

**Comment by skrchnavy** [comment]
#420 approved, when merge this will be closed

**Comment by skrchnavy** [comment]
#420 merged into develop, closing
