### ISSUE TITLE
No extractors in new system ?

### ISSUE THREAD

**Issue by redskate** [UnifiedViews/Core#422]
Hi 

I followed the installations instructions in https://grips.semantic-web.at/display/UDDOC/Installation+Guide and got (more or less) a running system under OSX Yosemite / tomcat 8 / Java 8.

I installed the modules Plugin-DevEnv, Core, Plugins, Packages errorfree.

In this new running system I wanted to create a pipeline.
Unfortunately my list of extractors/transformers/loaders (DPU Templates Tree) is empty. 
Insted I was expecting it being like in https://grips.semantic-web.at/display/UDDOC/3.+DPU+Templates+Section#id-3.DPUTemplatesSection-details

I am working under an administrator user (role=1) which should see the whole DPU template Tree inside the pipeline creation dialog.

I also noticed that the table UNIFIEDVIEWS.DPU_TEMPLATE is empty.

Furthermore I installed UNIFIEDVIEWS also on an ubuntu virtual machine - here are the URLS of both installations (please handle respectfully):
http://82.192.234.100:25818/unifiedviews/#!PipelineEdit/New - OSX
http://82.192.234.100:45380/unifiedviews/#!PipelineEdit/New - LINUX

The only error I get (in the frontend logs) is

2015-06-20 16:00:56,887 [localhost-startStop-1] ERROR c.c.m.x.o.commons.app.module.osgi.OSGIModuleFacade - Wrong directory path: /Users/fabio/Documents/workspace/UNIFIEDVIEWS/Core/target/lib/lib

Althaugh modult.path is set as the installation guide suggests:
module.path = /Users/fabio/Documents/workspace/UNIFIEDVIEWS/Core/target

What should I do in order to see the whole default DPU template Tree?
Thank you for your advice !!

Fabio

**Comment by tomas-knap** [comment]
Hi Fabio, 

thanks for your interest, currently, if you install it from sources, you have to also checkout https://github.com/UnifiedViews/Plugins repository. Then by running mvn clean install on the root pom.xml of the Plugins repository, all DPUs will be prepared in "target" folders. You may then 1) individually import selected DPUs (JAR files) via GUI of UnifiedViews (DPUTemplate -> Create DPU template") or 2) pack the generated DPUs inside a zip archive, which may be then imported via GUI (DPUTemplate -> Create DPU template -> zip folder) - when importing zip archive, it basically tries to import all JAR files (DPUs) in the zip archive regardless of the folder in which they are.

I will update Installation Guide.

**Comment by tomas-knap** [comment]
Also you can install UnifiedViews from Deb packages, https://github.com/UnifiedViews/Packages. This will install UnifiedViews + Plugins.

**Comment by redskate** [comment]
Hi Tomas - thank you very much for your hints. Now I understood where to upload the modules.

Indeed I could load one-by-one all the transformers. But could not load the other ones - what I primarily need are the extractors and the loaders. Please see the exception below occurred under OSX.

What is wrong? Shell I recompile?

Thanks
Fabio



ERROR c.c.m.x.o.commons.app.module.DPUModuleManipulator - Failed to load new DPU bundle.
cz.cuni.mff.xrg.odcs.commons.app.module.ModuleException: org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-tabularToRelational_2.0.1 [20]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.loadClass(BundleContainer.java:135) ~[commons-app-2.0.3.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.getInstance(OSGIModuleFacade.java:153) ~[commons-app-2.0.3.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.module.DPUModuleManipulator.create(DPUModuleManipulator.java:144) ~[commons-app-2.0.3.jar:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DPUCreate.importDPU(DPUCreate.java:590) [DPUCreate.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DPUCreate.access$900(DPUCreate.java:57) [DPUCreate.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.components.DPUCreate$4.buttonClick(DPUCreate.java:497) [DPUCreate$4.class:na]
        at cz.cuni.mff.xrg.odcs.frontend.gui.AuthAwareButtonClickWrapper.buttonClick(AuthAwareButtonClickWrapper.java:47) [AuthAwareButtonClickWrapper.class:na]
        at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.ui.Button.fireClick(Button.java:393) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.ui.Button$1.click(Button.java:57) [vaadin-server-7.3.7.jar:7.3.7]
        at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:287) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) [vaadin-server-7.3.7.jar:7.3.7]
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
        at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:109) [ODCSApplicationServlet.class:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.15]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.15]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.15]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.15]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.15]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.15]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.15]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.15]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.15]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.15]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.15]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [catalina.jar:8.0.15]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085) [tomcat-coyote.jar:8.0.15]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat-coyote.jar:8.0.15]
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222) [tomcat-coyote.jar:8.0.15]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556) [tomcat-coyote.jar:8.0.15]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513) [tomcat-coyote.jar:8.0.15]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.15]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-t-tabularToRelational_2.0.1 [20]" could not be resolved. Reason: Missing Constraint: Import-Package: org.apache.commons.lang3; version="[3.0.0,4.0.0)"
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolverError(AbstractBundle.java:1332) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.getResolutionFailureException(AbstractBundle.java:1316) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:323) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:300) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:292) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.loadClass(BundleContainer.java:132) ~[commons-app-2.0.3.jar:na]
        ... 50 common frames omitted

**Comment by tomas-knap** [comment]
Fabio, to your problems with certain DPUs, which version of Core, Plugins-devEnv and Plugins did you checked out? Did you use "master" branch in all these cases?

**Comment by redskate** [comment]
Hi Tomas

I cloned the latest version by issuing
git clone https://github.com/UnifiedViews/Core.git
git clone https://github.com/UnifiedViews/Plugins.git
git clone https://github.com/UnifiedViews/Plugin-DevEnv.git
git clone https://github.com/UnifiedViews/Packages.git
git clone https://github.com/UnifiedViews/Maven-Repo.git

I think - this is master 

Thank you 
Fabio

**Comment by redskate** [comment]
Please don't leave me alone ;)

**Comment by skrchnavy** [comment]
Hi @redskate 

from the log I can see that your import failed in t-tabular. Please check https://github.com/UnifiedViews/Plugins/blob/master/t-tabular/README.md for this DPU and at the end you can find some notes how to install this DPU (fulfil prerequisites).

**Comment by skrchnavy** [comment]
Sorry, I overlooked it is another DPU. t-tabularToRelational.

we have to check compatibility of versions of Core (2.0.3) and plugins (2.0.1)
If you want to download plugins prebuilt in maven repo, please download them from http://maven.eea.sk/artifactory/public/eu/unifiedviews/plugins/

**Comment by redskate** [comment]
Hi @skrchnavy, thank you for this.
Indeed I discovered some manual builds to do, I did them (like the ojdbc7.jar from oracle to install), cleaned everything and re-issued "mvn clean install -P java8" at the main Plugin directory.

The log file of this command is here:  http://82.192.234.100:25999/uv/install_log.txt

It seems that so it is not the right way to install.. I will consider your suggestion to take the plugins from maven.ees.sk

**Comment by redskate** [comment]
Hi Tomas

none of the plugins from the jar directory seem to work when uploaded in the UNIFIED view client.

Failed to load DPU because of exception:org.osgi.framework.BundleException: The bundle "eu.unifiedviews.plugins.uv-e-silkLinker_1.3.1 [4]" could not be resolved. Reason: Missing Constraint: Import-Package: eu.unifiedviews.dataunit; version="[1.0.0,2.0.0)"

How can I solve this missing contraint please?

Thanks
Fabio

**Comment by skrchnavy** [comment]
SilkLinker is not supported in 2.X version of UV, version 1.3.X of silk linker requires UV 1.3.X and newer.

**Comment by redskate** [comment]
what is my UV ???

Am 25.6.15 um 19:05 schrieb skrchnavy:

**Comment by skrchnavy** [comment]
UV = UnifiedViews, I expect you have 2.X version when building from latest master branch.

**Comment by tomas-knap** [comment]
Fabio, so regarding your current situation, all plugins can be successfully imported to UnifiedViews except of SilkLinker? 
In this week, I will be updating SilkLinker, so by the end of this week I will send you a link to the updated SilkLinker you may use with your current version of UnifiedViews 2.X. Is it ok for you if you have working SilkLinker this week?

**Comment by redskate** [comment]
Hi Tomas

these are great news!

Do you mean the recompiled plugins will then be fitting to the load
process of the (compiled) source code in github?

No, silkLinker was just one of several examples which did not load. I do
not need it particularly. I just need (for the moment) extrators from
files, csv, relational, xml/rdf ...

Thank you for this and maybe a short message when done would be great!

Thanks again
Have a nice day
Fabio




Am 29.6.15 um 08:27 schrieb Tomas Knap:

**Comment by skrchnavy** [comment]
@redskate: Plugins v2.1.0 were released so you can use those versions. See https://github.com/UnifiedViews/Plugins/releases/tag/UV_Plugins_v2.1.0
Some of DPUs you reported as missing are not extractors but transformers, Extractors are those that goes outside UV workspace.

Can we close this issue? If you miss any generic DPU please create issue in Plugins repository

**Comment by redskate** [comment]
Hi !

Thank you for commicating this to me!
I will asap reconsider and rebuild UV using the new pieces :)

Yes, you can close the issue :)
Thanks
Fabio


Am 10.7.15 um 13:26 schrieb skrchnavy:
