### ISSUE TITLE
Performance issue:  java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Jan-Marcek** [UnifiedViews/Core#431]
When I start tomcat (```service unifiedviews-frontend start ```) from https://github.com/UnifiedViews/Packages/tree/master/unifiedviews-webapp-shared then I get ``` java.lang.OutOfMemoryError```. Memory requirement of unifiedviews frontend was raised from version 2.0.1 to 2.1.0. (in 2.0.1 there was no problem with memory) 
It happened in three different VM instances. 

Tomcat uses default HeapSpace: ``` -Xmx128M ```

workaround: add parameter ```-Xmx``` to setenv.sh into tomcat in our case: ```/usr/share/unifiedviews/tomcat/bin/setenv.sh``` 
e.g. ```-Xmx512M```

version: UV 2.1.0

```
SEVERE: Error waiting for multi-thread deployment of context descriptors to complete
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:574)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:470)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1413)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:313)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:401)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:346)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1159)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:785)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1595)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1585)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.apache.tomcat.util.bcel.classfile.LineNumberTable.<init>(LineNumberTable.java:70)
        at org.apache.tomcat.util.bcel.classfile.Attribute.readAttribute(Attribute.java:144)
        at org.apache.tomcat.util.bcel.classfile.Code.<init>(Code.java:86)
        at org.apache.tomcat.util.bcel.classfile.Attribute.readAttribute(Attribute.java:140)
        at org.apache.tomcat.util.bcel.classfile.FieldOrMethod.<init>(FieldOrMethod.java:58)
        at org.apache.tomcat.util.bcel.classfile.Method.<init>(Method.java:72)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.readMethods(ClassParser.java:268)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:128)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2049)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1931)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1899)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1885)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1281)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:855)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:346)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5172)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        ... 4 more

Jun 24, 2015 3:48:11 PM org.apache.catalina.startup.HostConfig deployDescriptors
SEVERE: Error waiting for multi-thread deployment of context descriptors to complete
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:574)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:470)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1413)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:313)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:401)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:346)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:1159)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:785)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1595)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1585)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:178)
        at java.util.jar.JarInputStream.getBytes(JarInputStream.java:115)
        at java.util.jar.JarInputStream.checkManifest(JarInputStream.java:94)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:86)
        at java.util.jar.JarInputStream.<init>(JarInputStream.java:62)
        at org.apache.catalina.util.ExtensionValidator.getManifest(ExtensionValidator.java:392)
        at org.apache.catalina.util.ExtensionValidator.validateApplication(ExtensionValidator.java:193)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5106)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:618)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:650)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        ... 4 more

Jun 24, 2015 3:48:12 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-127.0.0.1-28080"]
Jun 24, 2015 3:48:12 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-28009"]
Jun 24, 2015 3:48:12 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 15763 ms
Exception in thread "http-bio-127.0.0.1-28080-exec-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at sun.nio.cs.ext.GBK.<clinit>(GBK.java:95)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at sun.nio.cs.AbstractCharsetProvider.lookup(AbstractCharsetProvider.java:142)
        at sun.nio.cs.AbstractCharsetProvider.access$000(AbstractCharsetProvider.java:45)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-bio-127.0.0.1-28080-exec-1"
Exception in thread "http-bio-127.0.0.1-28080-exec-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-9" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-11" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-13" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-bio-127.0.0.1-28080-exec-15" java.lang.OutOfMemoryError: GC overhead limit exceeded

```

**Comment by Jan-Marcek** [comment]
Not working with ```-Xmx128M```,``` -Xmx256M```,``` -Xmx384M ```
Working with ```-Xmx512M ```

**Comment by skrchnavy** [comment]
@tomas-knap  (@pskoda) do you remember any feature that caused such big increase of memory usage from 2.0 to 2.1 version? Could be Vaadin upgrade root cause of this?

**Comment by skrchnavy** [comment]
This is not fixed, just workaround provided to start it but memory is too high (512MB) for such component.

**Comment by Jan-Marcek** [comment]
We found that frontend is not the problem. It works with -Xmx128M.  
The problem is with master.
