### ISSUE TITLE
Export/Import - Importing pipeline with name that already exist causes error

### ISSUE THREAD

**Issue by mvi-eea-sk** [UnifiedViews/Core#457]
Steps reproduce:
1. import some pipeline from zip file
2. try to import the same zip file second time - error

```
2015-07-14 09:37:37,266 ["http-bio-8080"-exec-8] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ppl_model_name_key"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105) ~[commons-dbcp-1.4.jar:1.4]
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:890) ~[commons-app-2.1.1-SNAPSHOT.jar:na]
...
	at cz.cuni.mff.xrg.odcs.commons.app.facade.PipelineFacadeImpl.save(PipelineFacadeImpl.java:184) ~[commons-app-2.1.1-SNAPSHOT.jar:na]
...
	at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService.importPipeline(ImportService.java:143) ~[commons-app-2.1.1-SNAPSHOT.jar:na]
	at cz.cuni.mff.xrg.odcs.commons.app.pipeline.transfer.ImportService.importPipeline(ImportService.java:85) ~[commons-app-2.1.1-SNAPSHOT.jar:na]
...
```

This is caused because the name has unique constraint restriction

According to sto_82 error message should be displayed: "Pipeline with such name already exists in the system" and the import button should be disabled

Related with #356

**Comment by mvi-eea-sk** [comment]
duplicate of #471
