### ISSUE TITLE
previously working dpu throws class not found exception now

### ISSUE THREAD

**Issue by yyz1989** [UnifiedViews/Core#542]
Hi there,

I just encountered a strange problem. A dpu is suddenly broken for some reason and reports class not found exception. It was working properly yesterday, but it is broken today without any change on the server side between this two periods. I tried to restart the frontend and backend, but both do not work. I may try to recompile and reinstall the dpu now. But I think it is necessary to make you aware of this issue. I installed all unifiedviews component from source code, the versions are all latest releases. Thank you very much.

Regards,
Yang

```
2015-10-24 10:43:03,354 [dpu: uv-e-relationalFromSql] ERROR exec:69 dpu:84 c.c.m.x.o.b.pipeline.event.PipelineFailedEvent - Pipeline failed on DPU 'uv-e-relationalFromSql' because of the module exception
cz.cuni.mff.xrg.odcs.commons.app.module.ModuleException: java.lang.ClassNotFoundException: eu.unifiedviews.plugins.extractor.relationalfromsql.RelationalFromSql cannot be found by eu.unifiedviews.plugins.uv-e-relationalFromSql_2.1.3
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.loadClass(BundleContainer.java:164) ~[commons-app-2.2.0.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.OSGIModuleFacade.getInstance(OSGIModuleFacade.java:183) ~[commons-app-2.2.0.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.dpu.DPUInstanceRecord.loadInstance(DPUInstanceRecord.java:139) ~[commons-app-2.2.0.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.loadInstance(DPUExecutor.java:179) [backend-2.2.0.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:331) [backend-2.2.0.jar:na]
        at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:468) [backend-2.2.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.ClassNotFoundException: eu.unifiedviews.plugins.extractor.relationalfromsql.RelationalFromSql cannot be found by eu.unifiedviews.plugins.uv-e-relationalFromSql_2.1.3
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
        at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:340) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212) ~[org.eclipse.osgi-3.9.0.v20130305-2200.jar:na]
        at cz.cuni.mff.xrg.odcs.commons.app.module.osgi.BundleContainer.loadClass(BundleContainer.java:162) ~[commons-app-2.2.0.jar:na]
        ... 6 common frames omitted
```

**Comment by tomas-knap** [comment]
If the DPU was working once and you did not modify the DPU, access rights to the folder with the DPU, and also did not modify Core code, it should work also for the second time. Is your tomcat in good condition, aren't there any suspicious logs, such as lack of PermGen space? 

Even if one DPU cannot be loaded, frontend/backend should run normally writing only to the log that certain DPU cannot be loaded. Was this the situation in your case? Or did frontend/backend fail to start completely in your case? Can you please attach logs?

**Comment by yyz1989** [comment]
@tomas-knap 
Hi Tomas, thanks a lot. I cannot reproduce that error any more after I restarted UnifiedViews. It is possible that this problem is also caused by the memory issue I consulted to you a few days ago. So let's close this issue for the moment, and see when it will happen again.
