### ISSUE TITLE
support for bind

### ISSUE THREAD

**Issue by bertvannuffelen** [UnifiedViews/Core#543]
Hi,
using the debug mode of UV 2.1.3 I reach an null-pointer exception when posing the following query in the debug window. 
Without the bind it works.

I wonder if Sesame is supporting "Bind".

PREFIX dta: <http://dta.com>
PREFIX skos:<http://www.w3.org/2004/02/skos/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

select *
where {
 ?r a dta:Request.
 ?r dta:id ?id.
 BIND(URI(CONCAT("http://dta.com/DTA/agent/", ?id)) AS ?agent).

} limit 10

kind regards,

Bert

**Comment by tomas-knap** [comment]
Bert, it should support. Can you please paste the exception you got? Was it t-sparqlSelect DPU which thrown the exception?

**Comment by bertvannuffelen** [comment]
Tomas, I tested further and I found the exact problem.
The dta:id value is typed as xsd:int.
And then the concat function gets into trouble. 
In a DPU this results in no triples, in the debug mode this triggers a null-pointer exception.

**Comment by tomas-knap** [comment]
The issue appear during querying the data unit via admin interface.

The problem: When the query was executed, concat function gets into trouble because the dta:id value is type as xsd:int (see above). As a result, no result was produced, but the admin interface expect some result (the query "has not null result." as in the logs).

Solution: It should for sure not throw NullPointerException, but it should show empty result and if possible, it should show the reasone of this (is provided by openRDF)

The relevant part of the log: 

```
2015-10-27 14:17:11,606 [http-bio-127.0.0.1-28080-exec-1] DEBUG c.c.m.x.o.f.container.rdf.RepositoryFrontendHelper - Query PREFIX codi: <http://data.com/data/concept/> 
PREFIX codi-s: <http://data.com/data/conceptScheme/> 
PREFIX dta: <http://data.com/def/ontology/DTA/>
PREFIX skos:<http://www.w3.org/2004/02/skos/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

select * 
where {
 ?r a dta:Request.
 ?r dta:id ?id.
 BIND(URI(CONCAT("http://data.com/id/DTA/agent/", ?id)) AS ?agent).

} LIMIT 15  has not null result.
2015-10-27 14:17:11,607 [http-bio-127.0.0.1-28080-exec-1] DEBUG c.c.mff.xrg.odcs.frontend.container.rdf.RDFQuery - Loading of items finished.
2015-10-27 14:17:11,630 [http-bio-127.0.0.1-28080-exec-1] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
java.lang.NullPointerException: null
	at cz.cuni.mff.xrg.odcs.frontend.gui.components.RDFQueryView$4.getStyle(RDFQueryView.java:230) ~[RDFQueryView$4.class:na]
	at com.vaadin.ui.CustomTable.paintRow(CustomTable.java:3875) ~[filteringtable-0.9.11.v7.jar:7.3.7]
	at com.vaadin.ui.CustomTable.paintRows(CustomTable.java:3703) ~[filteringtable-0.9.11.v7.jar:7.3.7]
	at com.vaadin.ui.CustomTable.doPaintContent(CustomTable.java:3291) ~[filteringtable-0.9.11.v7.jar:7.3.7]
	at com.vaadin.ui.CustomTable.paintContent(CustomTable.java:3260) ~[filteringtable-0.9.11.v7.jar:7.3.7]
	at org.tepi.filtertable.FilterTable.paintContent(FilterTable.java:74) ~[filteringtable-0.9.11.v7.jar:0.9.11.v7]
	at com.vaadin.server.LegacyPaint.paint(LegacyPaint.java:65) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.LegacyUidlWriter.write(LegacyUidlWriter.java:82) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:116) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:151) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:99) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406) ~[vaadin-server-7.3.7.jar:7.3.7]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305) [vaadin-server-7.3.7.jar:7.3.7]
	at cz.cuni.mff.xrg.odcs.frontend.ODCSApplicationServlet.service(ODCSApplicationServlet.java:123) [ODCSApplicationServlet.class:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [tomcat-servlet-api-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421) [tomcat-catalina-7.0.56.jar:7.0.56]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote-7.0.56.jar:7.0.56]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote-7.0.56.jar:7.0.56]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) [tomcat-coyote-7.0.56.jar:7.0.56]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote-7.0.56.jar:7.0.56]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
2015-10-27 14:17:11,630 [http-bio-127.0.0.1-28080-exec-1] INFO  c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - Request (3693) finished processing in: 147 ms
2015-10-27 14:17:11,630 [http-bio-127.0.0.1-28080-exec-1] DEBUG c.c.mff.xrg.odcs.frontend.ODCSApplicationServlet - Request (/unifiedviews/UIDL/) URI

```

**Comment by jindrichmynarz** [comment]
`CONCAT()` requires its arguments to be `xsd:string`s (see [the spec](http://www.w3.org/TR/sparql11-query/#func-concat)). Sesame is sensitive about this, so you need to explicitly convert any non-string literal to string via `STR()`. You may want to raise this upstream with Sesame, as it could throw a better exception.
