### ISSUE TITLE
saving pipelines triggers sql exception

### ISSUE THREAD

**Issue by GSC-DEVARCH** [UnifiedViews/Core#568]
Hi,

after using some time the 2.3.0 release we get on saving pipelines the following exception:

2016-01-13 10:14:41,172 [http-bio-127.0.0.1-28080-exec-6] WARN  org.eclipse.persistence.logging.default - 2016-01-13 10:14:41.172--UnitOfWork(1750418939)--
2016-01-13 10:14:41,175 [http-bio-127.0.0.1-28080-exec-6] ERROR cz.cuni.mff.xrg.odcs.frontend.AppEntry - Uncaught exception
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`unifiedviews`.`exec_context_dpu`, CONSTRAINT `FK_exec_context_dpu_dpu_instance_id` FOREIGN KEY (`dpu_instance_id`) REFERENCES `dpu_instance` (`id`))
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_91]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870) ~[mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806) ~[mysql-connector-java-5.1.37.jar:5.1.37]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470) ~[mysql-connector-java-5.1.37.jar:5.1.37]

kind regards,

Bert

**Comment by bertvannuffelen** [comment]
a more deeper observation, led to the following case:

the exception is triggered after deleting a dpu from the pipeline and then trying to save it.

kind regards,

Bert
